import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@/auth'
import connectDB from '@/lib/db/mongoose'
import InfluencerProfile from '@/lib/db/models/InfluencerProfile'
import User from '@/lib/db/models/User'

const profileSchema = z.object({ bio: z.string().max(1000).optional(), city: z.string().max(80).optional(), state: z.string().max(80).optional(), niche: z.string().max(100).optional(), categories: z.array(z.string().max(80)).max(20).optional(), languages: z.array(z.string().max(50)).max(20).optional(), socialAccounts: z.array(z.object({ platform: z.enum(['INSTAGRAM', 'YOUTUBE', 'FACEBOOK', 'TWITTER', 'LINKEDIN', 'TIKTOK', 'OTHER']), handle: z.string().max(100), url: z.string().max(300).optional(), followers: z.number().min(0), engagementRate: z.number().min(0).max(100).optional() })).max(10).optional(), pricing: z.object({ reel: z.number().min(0).optional(), post: z.number().min(0).optional(), story: z.number().min(0).optional(), youtubeVideo: z.number().min(0).optional() }).optional(), portfolio: z.array(z.object({ title: z.string().max(120), url: z.string().max(300), platform: z.string().max(50).optional(), type: z.string().max(50).optional() })).max(20).optional() })
const completion = (p: any, name?: string, phone?: string) => { const fields = [name, phone, p?.city, p?.state, p?.niche, p?.bio, p?.categories?.length, p?.languages?.length, p?.socialAccounts?.length, p?.totalFollowers > 0, p?.avgEngagementRate > 0, p?.portfolio?.length, p?.pricing?.reel || p?.pricing?.post]; return Math.round(fields.filter(Boolean).length / fields.length * 100) }
export async function GET() { const session = await auth(); if (!session?.user?.id || (session.user as any).role !== 'INFLUENCER') return NextResponse.json({ error: 'Unauthorized' }, { status: 403 }); await connectDB(); const [profile, user] = await Promise.all([InfluencerProfile.findOne({ userId: session.user.id }).lean(), User.findById(session.user.id).select('name email phone').lean()]); return NextResponse.json({ success: true, data: { profile, user, completion: completion(profile, user?.name, user?.phone) } }) }
export async function PATCH(request: NextRequest) { const session = await auth(); if (!session?.user?.id || (session.user as any).role !== 'INFLUENCER') return NextResponse.json({ error: 'Unauthorized' }, { status: 403 }); const parsed = profileSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: 'Invalid profile data.' }, { status: 400 }); await connectDB(); const data: any = parsed.data; if (data.socialAccounts) data.totalFollowers = data.socialAccounts.reduce((total: number, account: any) => total + account.followers, 0); if (data.socialAccounts?.length) data.avgEngagementRate = data.socialAccounts.reduce((total: number, account: any) => total + (account.engagementRate || 0), 0) / data.socialAccounts.length; const profile = await InfluencerProfile.findOneAndUpdate({ userId: session.user.id }, { $set: data }, { new: true, upsert: true, setDefaultsOnInsert: true }).lean(); const user = await User.findById(session.user.id).select('name phone').lean(); return NextResponse.json({ success: true, data: { profile, completion: completion(profile, user?.name, user?.phone) } }) }
